---
- hosts: localhost
  become: true
  tasks:
    - name: install web components
      yum: name{{item}}
      with_items:
        - python-pip
        - python-virutalenv
      vars:
        ansible_python_interpreter: /usr/bin/python2.7
    - pip: requirements=/home/ansadmin/opt/python/rest_api/requirements.txt virtualenv=/home/ansadmin/opt/python/rest_api/.venv
    - name: start Flask
      shell: /home/ansadmin/opt/python/rest_api/bootstrap.sh
